apiVersion: kustomize.config.k8s.io/v1beta1
bases:
  - ../base
kind: Kustomization
patches:
  - path: patch-ingress.yml
imageTags:
  - name: europe-west3-docker.pkg.dev/swr-schulung-basic-1/swr-schulung-basic-1/digitalegarage/quickstart-go-graphql
    newTag: a4eb94a3817ffd46abe802dfd1f5bf194a95b181