apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-listener
  annotations:
    tekton.dev/payload-validation: "false"
spec:
  serviceAccountName: tekton-triggers-sa
  triggers:
    - name: github-listener
      bindings:
        - ref: github-binding # TriggerBinding
      template:
        ref: github-template # TriggerTemplate