apiVersion: v1
kind: Secret
metadata:
  name: github-interceptor-secret
  annotations:
    vault.security.banzaicloud.io/vault-addr: "https://secrets.s.pub-dev.tech"
    vault.security.banzaicloud.io/vault-role: "default"
    vault.security.banzaicloud.io/vault-agent: "false"
    vault.security.banzaicloud.io/vault-path: "kubernetes"
    # echo 'secrets/data/kubernetes/infra/tekton#github-webhook-pass' | base64
    changenotation.secret.vault.pub.tech/ssh-privatekey: "c2VjcmV0cy9kYXRhL2t1YmVybmV0ZXMvaW5mcmEvdGVrdG9uI2dpdGh1Yi13ZWJob29rLXBhc3MK"
type: Opaque
stringData:
  secretToken: vault:secrets/data/kubernetes/infra/tekton#github-webhook-pass
